config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'portfolios/angular', to: 'portfolios#angular'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank?}

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image
  #query to the db using scope
  def self.angular
    where(subtitle: "Angular")
  end
  #this method below does the same
  scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails")}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_items = Portfolio.new
    3.times { @portfolio_items.technologies.build }
  end

  def create
    @portfolio_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio is now life"}
      else
        format.html { render :new}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_items.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_items.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Item was successfully deleted.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                      )
  end

  def set_portfolio_item
    @portfolio_items = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_items) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li><%= technology_form.label :name %></li>
    <li><%= technology_form.text_field :name %></li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>

<h3><%= portfolio_item.subtitle %></h3>

<p><%= portfolio_item.body %></p>

<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>

<%= link_to "Edit item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to "Delete item", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<hr>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Item</h1>
<%= link_to "Create new item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure that you want to destroy the item #{portfolio_item.title}"} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1> Edit this portfolio item </h1>

<%= render 'form', portfolio_item: @portfolio_items %>

app/views/portfolios/index.html.erb
<h1>Portfolio items </h1>

<%= link_to "Create new item", new_portfolio_path if logged_in?(:site_admin) %>

<%= render partial: "portfolio_item", collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1> Create a new portfolio item </h1>


<%= render 'form', portfolio_item: @portfolio_items %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_items.main_image unless @portfolio_items.main_image.nil? %>

<h1><%= @portfolio_items.title %></h1>

<em><%= @portfolio_items.subtitle %></em>
<p><%= @portfolio_items.body %></p>

<h2>Tech used:</h2>
<%- @portfolio_items.technologies.each do |t| %>
  <p> <%= t.name %> </p>
<% end %>

<%= link_to "Edit item", edit_portfolio_path(@portfolio_items) if logged_in?(:site_admin) %>
<%= link_to "Delete item", portfolio_path(@portfolio_items), method: :delete, data: { confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<hr>
<%= params.inspect %>
<hr>
<%= session.inspect %>